### PR TITLE
Fix meta version/date formatting in index.qmd

### PR DESCRIPTION
**Pull request by Alanocallaghan**

### CODE REVIEW

**Comment by Alanocallaghan** [comment]
This just fixes the current text on the rendered index.html: 

> Calculus with Julia version {{< meta version }}, produced on {{< meta

**Comment by jverzani** [comment]
Thanks!

**Comment by Alanocallaghan** [comment]
Thanks for the book, seems like it'll be super useful

**Comment by jverzani** [comment]
Great. Let me know if things could be better explained or something could be added.

**Pull request merged**
