### PR TITLE
functions chapter edits

### PR DESCRIPTION
**Pull request by AndrewWasHere**
I stumbled upon the out of date readthedocs links when I went to investigate your description of the ternary operator. A quick grep of the quarto source shows readthedocs links in other chapters that you probably want to update to their corresponding julialang.org links. (This also begs the question, how long have you been writing these notes?)

On line 202, you claim that both expressions are evaluated in the ternary operator. I don't think this is the case, and I couldn't find any mention of it in the documentation. Or I'm badly misinterpreting what you meant with that statement. The way I interpreted that sentence was that if you have the following:
```julia
x = a > 0 ? foo() : bar()
```
"both expressions are evaluated" means `foo()` and `bar()` will get called, but only one return value will get assigned to `x`. And I'm pretty confident that this is not how it works.

I also don't think you can substitute a short circuit for a ternary directly, because they're logically different. Ternary statements are dependent on the condition before the `?`. Short circuits depend on the value of the expression before the `&&` or `||` and that expression (as well as the one after the `&&` or `||`) has to be a boolean.

That's a long winded way of saying you may want to revisit the paragraph on line 202.

On line 631, you mention pipes as a way to do functional composition, but you don't mention actual functional composition with circ notation. i.e.
```julia
(f ∘ g)(x)
```
You have questions about both at the end of the chapter, though.

### CODE REVIEW

**Comment by jverzani** [comment]
Thanks for this.

These notes have been worked on and off for quite some time. They grew out of some notes I had written for a class back in 2014 or so (v0.4?) and have been modified over time. Thanks for catching these links. I'll do a grep to see if others need finding. The presentation has varied from home-grown, to Pluto notebooks (which are kind of annoying to write for due to the need for avoiding the repeated use of names), and finally to quarto, which I'm fond of. 

I'll have a look at the composition operator usage. That certainly got added in along the way, but maybe not in the correct place. 

I'll also have a look at the ternary operator comment on 202.  They don't evaluate both sides, as you say.

Thanks again!

**Comment by AndrewWasHere** [comment]
Quarto looks nice. It reminds me a lot of org-mode on Emacs, only with better publishing knobs. The VS Code plugin is pretty slick, too. I may have to investigate replacing the standard Jekyll backend for my Github site with Quarto because it addresses a lot of shortcomings of Jekyll when it comes to code demonstration posts.

And before you make any assumptions, my answer to "Emacs or vi?" is "yes."

**Comment by jverzani** [comment]
I'm pretty impressed with quarto, though I prefer the markdown of weave, and it can take awhile to process a document. I need to hook up the integration with CI, as for now, edits like yours which don't require re-running any code  should push changes to the docs automatically, as opposed to now where I run them locally and push. (So you won't see your improvements for a bit...)

But how you can agnostic on emacs or vi? I thought you had to choose sides like Mets or Yankees. :)

**Comment by AndrewWasHere** [comment]
I was solidly in the vi camp for a long time simply because that's what I learned at university. Then I discovered org-mode, which was compelling for its use cases, and evil mode (vi keybindings for emacs), which made the barrier to entry much lower (it's effectively reduced to learning some elisp for vi-ers -- or just copy and pasting examples into your .emacs or init.el file and remaining blissfully ignorant). I've used both vi and emacs long enough now that I see the benefits of both approaches.

I am not alone in this world. I know of at least one other person who is emacs-vi agnostic.

**Comment by jverzani** [comment]
It is a small but fortunate community. My fingers only speak emacs now, never having gotten the feel for vi. (The original interface for SPlus before R, if I recall my introduction correctly...)

**Pull request merged**
